services:
  - type: web
    name: taqia-portfolio
    env: node
    plan: free
    buildCommand: rm -rf build && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
